tblinalg: tblinalg::MatGrid Class Reference
tblinalg::MatGrid Class Reference
#include <mat_grid.hpp>
Public Member Functions
MatGrid ()
MatGrid (const size_t _spDim)
MatBlock Block (const size_t mIdx=0) const
MatBlock & Block (const size_t mIdx=0)
MatBlock operator() (const integer i0, const integer i1) const
MatBlock & operator() (const integer i0, const integer i1)
size_t MooreIDX (const integer i0, const integer i1) const
Public Attributes
size_t numNei_
std::vector< MatBlock > matGrid_
std::vector< size_t > blockLength
std::vector< size_t > blockOrg
Detailed Description
Definition at line 25 of file mat_grid.hpp.
Constructor & Destructor Documentation
tblinalg::MatGrid::MatGrid () inline
Definition at line 28 of file mat_grid.hpp.
References matGrid_.
     {
         std::vector< MatBlock > matGrid_(1);
     }
tblinalg::MatGrid::MatGrid (const size_t _spDim) inline
Definition at line 33 of file mat_grid.hpp.
References matGrid_, and numNei_.
                                 :numNei_(pow(3,_spDim))
     {
         matGrid_= std::vector< MatBlock >( numNei_ );
     }
Member Function Documentation
MatBlock tblinalg::MatGrid::Block (const size_t mIdx = 0) const inline
Definition at line 39 of file mat_grid.hpp.
References matGrid_, and numNei_.
Referenced by tblinalg::TBOperator::AddEntry(), tblinalg::TBOperator::Dim(), tblinalg::TBOperator::NumNonZero(), tblinalg::TBOperator::NumNonZeroInRow(), tblinalg::TBOperator::saveTxtCoo(), tblinalg::TBOperator::TBOperator(), and tblinalg::TBOperator::WriteIntoFile().
     {
         assert( mIdx< numNei_ );
         return  matGrid_[mIdx];
     }
MatBlock& tblinalg::MatGrid::Block (const size_t mIdx = 0) inline
Definition at line 46 of file mat_grid.hpp.
References matGrid_, and numNei_.
     {
         assert( mIdx< numNei_ );
         return  matGrid_[mIdx];
     }
MatBlock tblinalg::MatGrid::operator() (const integer i0, const integer i1) const inline
Definition at line 53 of file mat_grid.hpp.
References matGrid_, and MooreIDX().
     {
         kpm::integer mIdx=MooreIDX(i0, i1 );
         return  matGrid_[mIdx];
     }
MatBlock& tblinalg::MatGrid::operator() (const integer i0, const integer i1) inline
Definition at line 60 of file mat_grid.hpp.
References matGrid_, and MooreIDX().
     {
         kpm::integer mIdx=MooreIDX(i0, i1 );
         return  matGrid_[mIdx];
     }
size_t tblinalg::MatGrid::MooreIDX (const integer i0, const integer i1) const inline
Definition at line 66 of file mat_grid.hpp.
Referenced by operator()().
     {
         return   4 + i0*3 + i1 ;
     }
Member Data Documentation
size_t tblinalg::MatGrid::numNei_
Definition at line 71 of file mat_grid.hpp.
Referenced by Block(), and MatGrid().
std::vector< MatBlock > tblinalg::MatGrid::matGrid_
Definition at line 72 of file mat_grid.hpp.
Referenced by Block(), MatGrid(), and operator()().
std::vector<size_t> tblinalg::MatGrid::blockLength
Definition at line 73 of file mat_grid.hpp.
std::vector<size_t> tblinalg::MatGrid::blockOrg
Definition at line 74 of file mat_grid.hpp.
The documentation for this class was generated from the following file:
include/tblinalg/mat_grid.hpp