tblinalg: tblinalg::MatBlock Class Reference
tblinalg::MatBlock Class Reference
#include <mat_block.hpp>
Public Member Functions
MatBlock ()
MatBlock (const size_t _dim)
size_t Dim () const
void SetDim (const size_t _dim)
void SetMatBlock (std::vector< MatRow > _matBlock)
void SetMatRow (const size_t row, const MatRow _matRow)
MatRow & GetMatRow (const size_t row)
MatRow GetMatRow (const size_t row) const
Public Attributes
std::vector< MatRow > matBlock_
Detailed Description
Definition at line 14 of file mat_block.hpp.
Constructor & Destructor Documentation
tblinalg::MatBlock::MatBlock () inline
Definition at line 17 of file mat_block.hpp.
 {   }
tblinalg::MatBlock::MatBlock (const size_t _dim) inline
Definition at line 19 of file mat_block.hpp.
References matBlock_.
     {
         matBlock_=std::vector< MatRow >(_dim);
     }
Member Function Documentation
size_t tblinalg::MatBlock::Dim () const inline
Definition at line 25 of file mat_block.hpp.
References matBlock_.
Referenced by tblinalg::TBOperator::Dim(), GetMatRow(), and SetMatRow().
 { return matBlock_.size(); }
void tblinalg::MatBlock::SetDim (const size_t _dim) inline
Definition at line 28 of file mat_block.hpp.
References matBlock_.
Referenced by tblinalg::TBOperator::TBOperator().
     {
         matBlock_=std::vector< MatRow >(_dim);
     }
void tblinalg::MatBlock::SetMatBlock (std::vector< MatRow > _matBlock) inline
Definition at line 33 of file mat_block.hpp.
References matBlock_.
     {
         matBlock_=_matBlock;
     }
void tblinalg::MatBlock::SetMatRow (const size_t row, const MatRow _matRow) inline
Definition at line 38 of file mat_block.hpp.
References Dim(), and matBlock_.
     {
         assert( row <  Dim() );
         matBlock_[row]=_matRow;
     }
MatRow& tblinalg::MatBlock::GetMatRow (const size_t row) inline
Definition at line 44 of file mat_block.hpp.
References Dim(), and matBlock_.
Referenced by tblinalg::TBOperator::AddEntry(), tblinalg::TBOperator::NumNonZero(), tblinalg::TBOperator::NumNonZeroInRow(), tblinalg::TBOperator::saveTxtCoo(), and tblinalg::TBOperator::WriteIntoFile().
     {
         assert( row <  Dim() );
         return matBlock_[row];
     }
MatRow tblinalg::MatBlock::GetMatRow (const size_t row) const inline
Definition at line 50 of file mat_block.hpp.
References Dim(), and matBlock_.
     {
         assert( row <  Dim() );
         return matBlock_[row];
     }
Member Data Documentation
std::vector< MatRow > tblinalg::MatBlock::matBlock_
Definition at line 56 of file mat_block.hpp.
Referenced by Dim(), GetMatRow(), MatBlock(), SetDim(), SetMatBlock(), and SetMatRow().
The documentation for this class was generated from the following file:
include/tblinalg/mat_block.hpp