tblinalg: tblinalg::MatRow Class Reference
tblinalg::MatRow Class Reference
#include <mat_row.hpp>
Public Member Functions
MatRow ()
MatRow (const size_t _dim)
void AddMatTuple (MatTuple _matTuple)
void AddMatTuple (const size_t _col, complex _val)
MatRow SortRow ()
size_t Dim () const
MatTuple GetMatTuple (const size_t idx) const
MatTuple & GetMatTuple (const size_t idx)
Public Attributes
std::vector< MatTuple > matRow_
Detailed Description
Definition at line 15 of file mat_row.hpp.
Constructor & Destructor Documentation
tblinalg::MatRow::MatRow () inline
Definition at line 19 of file mat_row.hpp.
 {}
tblinalg::MatRow::MatRow (const size_t _dim) inline
Definition at line 21 of file mat_row.hpp.
References matRow_.
     {
         matRow_=std::vector< MatTuple >(_dim);
     }
Member Function Documentation
void tblinalg::MatRow::AddMatTuple (MatTuple _matTuple) inline
Definition at line 26 of file mat_row.hpp.
References matRow_.
Referenced by tblinalg::TBOperator::AddEntry(), tblinalg::TBOperator::ReadOpFromFile(), tblinalg::TBOperator::saveTxtCoo(), and tblinalg::TBOperator::WriteIntoFile().
     {
         matRow_.push_back( _matTuple );
     }
void tblinalg::MatRow::AddMatTuple (const size_t _col, complex _val) inline
Definition at line 31 of file mat_row.hpp.
References matRow_.
     {
         matRow_.push_back( MatTuple(_col , _val ) );
     }
MatRow tblinalg::MatRow::SortRow () inline
Definition at line 36 of file mat_row.hpp.
References matRow_.
Referenced by tblinalg::TBOperator::ReadOpFromFile(), tblinalg::TBOperator::saveTxtCoo(), and tblinalg::TBOperator::WriteIntoFile().
     {
         std::sort( matRow_.begin(), matRow_.end(), sortTuplebyCol());
         return *this;
     }
size_t tblinalg::MatRow::Dim () const inline
Definition at line 43 of file mat_row.hpp.
References matRow_.
Referenced by tblinalg::TBOperator::AddEntry(), GetMatTuple(), tblinalg::TBOperator::NumNonZero(), tblinalg::TBOperator::NumNonZeroInRow(), tblinalg::TBOperator::saveTxtCoo(), and tblinalg::TBOperator::WriteIntoFile().
     {
         return matRow_.size();
     }
MatTuple tblinalg::MatRow::GetMatTuple (const size_t idx) const inline
Definition at line 48 of file mat_row.hpp.
References Dim(), and matRow_.
Referenced by tblinalg::TBOperator::AddEntry(), tblinalg::TBOperator::Multiply(), tblinalg::TBOperator::NumNonZero(), tblinalg::TBOperator::NumNonZeroInRow(), tblinalg::TBOperator::saveTxtCoo(), and tblinalg::TBOperator::WriteIntoFile().
     {
         assert( idx< Dim() );
         return matRow_[idx];
     }
MatTuple& tblinalg::MatRow::GetMatTuple (const size_t idx) inline
Definition at line 55 of file mat_row.hpp.
References Dim(), and matRow_.
     {
         assert( idx< Dim() );
         return matRow_[idx];
     }
Member Data Documentation
std::vector< MatTuple> tblinalg::MatRow::matRow_
Definition at line 62 of file mat_row.hpp.
Referenced by AddMatTuple(), Dim(), GetMatTuple(), MatRow(), and SortRow().
The documentation for this class was generated from the following file:
include/tblinalg/mat_row.hpp