tblinalg: tblinalg::TBOperator Class Reference
tblinalg::TBOperator Class Reference
#include <tb_operator.hpp>
Public Member Functions
TBOperator ()
TBOperator (const size_t _spatial_dim)
TBOperator (const size_t _OPDim, const size_t _colBufferSize)
size_t BufferSize () const
size_t Dim () const
size_t TotNumOrbs () const
size_t RowDim () const
size_t RowOrigin () const
size_t RowEnd () const
void SetTotNumOrbs (const size_t _totNumOrbs)
void SetRowOrigin (const size_t _rowOrig)
void SetRowEnd (const size_t _rowEnd)
void SetRowDim (const size_t _rowDim)
void SetRowRange (const std::string ddFilename)
void AddEntry (const size_t row, const size_t col, const complex val)
void Rescale (const size_t dx, const size_t dy, const tblinalg::real shift, const tblinalg::real scal)
void Multiply (const integer dx, const integer dy, const real a, const std::vector< complex > &X, const real b, std::vector< complex > &Y)
void Multiply (const real a, const std::vector< complex > &X, const real b, std::vector< complex > &Y)
size_t NumNonZero ()
size_t NumNonZeroInRow (size_t row)
void ReadOpFromFile (const int dx, const int dy, const std::string opFilename)
void WriteIntoFile (std::string label)
void saveTxtCoo (std::string label)
void PrintTBOp (const integer dx, const integer dy)
void ReadOpFromFile (const std::string opFilename)
void PrintTBOp ()
void Rescale (const tblinalg::real shift, const tblinalg::real scal)
void SetMpiWorkspace (Indexes _bIdx)
Public Attributes
MatGrid matGrid
Private Attributes
size_t spatialDim_
size_t rowDim_
size_t rowOrig_
size_t rowEnd_
size_t colBufferSize_
size_t numNonZero_
size_t totNumOrbs_
size_t sourceColOrig
size_t destColOrig
std::vector< complex > destX
std::vector< complex > sourceX
MPI_Comm cartComm
Indexes bIdx
Detailed Description
Definition at line 30 of file tb_operator.hpp.
Constructor & Destructor Documentation
tblinalg::TBOperator::TBOperator () inline
Definition at line 41 of file tb_operator.hpp.
                   :
     numNonZero_(0),bIdx(3),matGrid(0),
     rowDim_(0), rowOrig_(0), rowEnd_(0)
     {}
tblinalg::TBOperator::TBOperator (const size_t _spatial_dim) inline
Definition at line 47 of file tb_operator.hpp.
                                            :
     numNonZero_(0),bIdx(3),matGrid(_spatial_dim),
     rowDim_(0), rowOrig_(0), rowEnd_(0)
     {}
tblinalg::TBOperator::TBOperator (const size_t _OPDim, const size_t _colBufferSize) inline
Definition at line 53 of file tb_operator.hpp.
References tblinalg::MatGrid::Block(), colBufferSize_, matGrid, tblinalg::MatBlock::SetDim(), SetRowDim(), and SetRowOrigin().
                                                                  :
     numNonZero_(0),bIdx(3),matGrid(0) ,
     rowDim_(0), rowOrig_(0), rowEnd_(0)
     {
         colBufferSize_ = _colBufferSize ;
         matGrid.Block().SetDim(_OPDim);
         SetRowOrigin(0);
         SetRowDim(_OPDim);
     }
Member Function Documentation
size_t tblinalg::TBOperator::BufferSize () const inline
Definition at line 63 of file tb_operator.hpp.
References colBufferSize_.
Referenced by AddEntry().
 {  return colBufferSize_;  }
size_t tblinalg::TBOperator::Dim () const inline
Definition at line 65 of file tb_operator.hpp.
References tblinalg::MatGrid::Block(), tblinalg::MatBlock::Dim(), and matGrid.
Referenced by NumNonZero(), saveTxtCoo(), and WriteIntoFile().
 { return matGrid.Block().Dim(); }
size_t tblinalg::TBOperator::TotNumOrbs () const inline
Definition at line 67 of file tb_operator.hpp.
References totNumOrbs_.
Referenced by ReadOpFromFile(), SetRowDim(), SetRowEnd(), and SetRowOrigin().
 {  return totNumOrbs_; }
size_t tblinalg::TBOperator::RowDim () const inline
Definition at line 69 of file tb_operator.hpp.
References rowDim_.
Referenced by Multiply(), PrintTBOp(), ReadOpFromFile(), Rescale(), and SetMpiWorkspace().
 { return rowDim_; }
size_t tblinalg::TBOperator::RowOrigin () const inline
Definition at line 71 of file tb_operator.hpp.
References rowOrig_.
Referenced by Multiply(), PrintTBOp(), ReadOpFromFile(), Rescale(), SetMpiWorkspace(), and SetRowDim().
 { return rowOrig_; }
size_t tblinalg::TBOperator::RowEnd () const inline
Definition at line 73 of file tb_operator.hpp.
References rowEnd_.
Referenced by ReadOpFromFile().
 { return rowEnd_; }
void tblinalg::TBOperator::SetTotNumOrbs (const size_t _totNumOrbs) inline
Definition at line 76 of file tb_operator.hpp.
References totNumOrbs_.
Referenced by ReadOpFromFile().
     {
         totNumOrbs_=_totNumOrbs;
     }
void tblinalg::TBOperator::SetRowOrigin (const size_t _rowOrig) inline
Definition at line 81 of file tb_operator.hpp.
References rowDim_, rowEnd_, rowOrig_, and TotNumOrbs().
Referenced by SetRowRange(), and TBOperator().
     {
         rowOrig_=_rowOrig;
         if ( rowOrig_ >= TotNumOrbs() )
             rowOrig_= TotNumOrbs() ;
         rowEnd_=rowOrig_ + rowDim_;
         if (rowEnd_ >= TotNumOrbs() )
         {
             rowEnd_= TotNumOrbs() ;
             std::cout<<"A mistake was made before!"<<std::endl;
         }
     }
void tblinalg::TBOperator::SetRowEnd (const size_t _rowEnd) inline
Definition at line 96 of file tb_operator.hpp.
References rowEnd_, and TotNumOrbs().
Referenced by SetRowRange().
     {
         rowEnd_=_rowEnd;
         if (rowEnd_ >= TotNumOrbs() )
         rowEnd_=TotNumOrbs();
     }
void tblinalg::TBOperator::SetRowDim (const size_t _rowDim) inline
Definition at line 103 of file tb_operator.hpp.
References rowDim_, rowEnd_, RowOrigin(), and TotNumOrbs().
Referenced by ReadOpFromFile(), SetRowRange(), and TBOperator().
     {
         rowDim_=_rowDim;
         rowEnd_= RowOrigin()+ _rowDim;
         if (rowEnd_ >= TotNumOrbs() )
             rowEnd_ = TotNumOrbs() ;
     }
void tblinalg::TBOperator::SetRowRange (const std::string ddFilename)
Definition at line 1 of file set_row_range.cpp.
References tblinalg::fileExists(), SetRowDim(), SetRowEnd(), and SetRowOrigin().
 {
     int rank, worldSize;
     MPI_Comm_rank(MPI_COMM_WORLD, &rank);
     MPI_Comm_size(MPI_COMM_WORLD, &worldSize);
     //Cheack if the file existas and open the file
     std::string
     localFilename= ddFilename+".DD";
     if ( ! fileExists(localFilename) )
     {
         std::cerr<<"File: "<<localFilename<<" not found, return -1;";
         std::exit(-1);
     }
     std::ifstream OpFile  (localFilename.c_str(), std::ofstream::binary);
     //Read the dimension of the matrix, and the total number
     size_t  Dom[3];
     OpFile>>Dom[0]>>Dom[1]>>Dom[2];
     size_t rowOrig,rowEnd;
     OpFile>>rowOrig;
     for ( size_t r=0; r<worldSize ;r++ )
     {
         OpFile>>rowEnd;
         if (r==rank)
         {
             SetRowOrigin(rowOrig);
             SetRowEnd(rowEnd);
             SetRowDim(rowEnd-rowOrig);
             OpFile.close();
             return ;
         }
     rowOrig=rowEnd;
     }
 };
void tblinalg::TBOperator::AddEntry (const size_t row, const size_t col, const complex val)
Definition at line 1 of file add_entry.cpp.
References tblinalg::MatRow::AddMatTuple(), tblinalg::MatGrid::Block(), BufferSize(), tblinalg::MatTuple::col, tblinalg::MatRow::Dim(), tblinalg::MatBlock::GetMatRow(), tblinalg::MatRow::GetMatTuple(), matGrid, and tblinalg::MatTuple::val.
     {
         MatRow matRow = matGrid.Block().GetMatRow(row);
         size_t rowSize= matRow.Dim() ;
         bool col_found = false;
         if ( rowSize == 0)
         {
             matRow.AddMatTuple(col,val);
             col_found = true;
         }
         else for(size_t elIdx=0; elIdx < rowSize ;elIdx++)
         {
             MatTuple elem = matRow.GetMatTuple(elIdx) ;
             if( elem.col == col )
             {
                 elem.val+= val ;
                 elIdx=rowSize;
                 col_found = true;
             }
         }
         if ( !col_found )
             matRow.AddMatTuple(col,val);
         if( matRow.Dim() > BufferSize() )
         {
             std::cerr   <<std::endl<<"Error:"
                         <<"Attempt to add element in row: "<< row<<std::endl
                         <<"with dimension "<<matRow.Dim()<<std::endl
                         <<"exceed the buffer size: "<< BufferSize()<<std::endl
                         <<"Choose another "
                         <<"buffer size or verify the hamiltonian"
                         <<std::endl;
             std::cerr<< "The row has the following elements"<<std::endl;
             for(size_t elIdx=0; elIdx < matRow.Dim() ;elIdx++)
             {
                 MatTuple elem = matRow.GetMatTuple(elIdx) ;
                 std::cerr<<row<<" "<<elem.col<<" "<<elem.val<<std::endl;
             }
             std::cerr<<std::endl;
             std::exit(-1);
         }
     matGrid.Block().GetMatRow(row)  =   matRow ;
     };
void tblinalg::TBOperator::Rescale (const size_t dx, const size_t dy, const tblinalg::real shift, const tblinalg::real scal)
Definition at line 1 of file rescale.cpp.
References tblinalg::MatTuple::col, matGrid, RowDim(), RowOrigin(), and tblinalg::MatTuple::val.
Referenced by Rescale().
 {
     for( size_t rowIdx= 0; rowIdx <RowDim() ; rowIdx++ )
     {
         const size_t row = rowIdx + RowOrigin() ;
         const size_t numElems = matGrid(dx,dy).GetMatRow(rowIdx).Dim();
         for( size_t elIdx=0; elIdx < numElems; elIdx++ )
         {
             MatTuple
             t = matGrid(dx,dy).GetMatRow(rowIdx).GetMatTuple(elIdx);
             if ( row  == t.col )
                     t.val -= shift ;
                 t.val*= scal ;
                 //Return to the tuple
                 matGrid(dx,dy).GetMatRow(rowIdx).GetMatTuple(elIdx).val =t.val ;
         }
     }
 };
void tblinalg::TBOperator::Multiply (const integer dx, const integer dy, const real a, const std::vector< complex > & X, const real b, std::vector< complex > & Y)
Definition at line 5 of file multiply.cpp.
References bIdx, tblinalg::MatTuple::col, destColOrig, tblinalg::MatRow::GetMatTuple(), matGrid, tblinalg::Indexes::ReduceToOne(), ROOT, RowDim(), RowOrigin(), and tblinalg::MatTuple::val.
Referenced by cheb_evolve().
 {
     const int rank = bIdx.ReduceToOne();
         if (rank == ROOT )
         {
             std::cout<<"Input X "<<std::endl;
             for(int r=0; r< RowDim() ; r++)
             if (X[ r  ].real()!=0 )
                 std::cout<<r<<" "<<X[ r  ]<<std::endl;
         }
     for( size_t rowIdx=0; rowIdx < RowDim() ; rowIdx++ )
     {
         Y[rowIdx]= Y[rowIdx]*b;
         const size_t numElems=matGrid(dx,dy).GetMatRow(rowIdx).Dim();
         const MatRow matrow = matGrid(dx,dy).GetMatRow(rowIdx);
         for( size_t elIdx=0; elIdx < numElems ; elIdx++ )
         {
             const MatTuple t    = matrow.GetMatTuple(elIdx);
             const integer colIdx= t.col-destColOrig;
             const complex val   = a*t.val ;
             if( rank == ROOT)
 //          if ( colIdx>= 0 && colIdx< RowDim() )
 //              if ( colIdx>= 0  && std::norm(X[colIdx])!=0 )
                     std::cout//<<"Y("<<rowIdx+RowOrigin()<<") = "
                              //<<b<<"* Y("<<rowIdx+RowOrigin()<<") + "<<a
                              //<<"* H("<< rowIdx+RowOrigin()<<","<<t.col<<")"
                              //<<" X("<<t.col<<")"<<std::endl
                              <<"RowDim"<<RowDim()<<" "
                              <<"a="<<a<<" b="<<b<<" colOrigin= "<<destColOrig<<std::endl
                               <<" aH("<< rowIdx+RowOrigin()<<","<<t.col<<")="<< val.real()
                              <<" X("<<colIdx<<")="<<X[colIdx].real()
                              <<" bY("<<rowIdx+RowOrigin()<<")="<<Y[rowIdx].real()<<std::endl;
             if ( colIdx>= 0 && colIdx< RowDim() )
                 Y[rowIdx]+= X[colIdx]*val;
         }
     }
 }
void tblinalg::TBOperator::Multiply (const real a, const std::vector< complex > & X, const real b, std::vector< complex > & Y)
Definition at line 57 of file multiply.cpp.
References Multiply(), and ROOT.
Referenced by Multiply().
 {
     const int rank = bIdx.ReduceToOne();
     //On-site multiplication
     if(rank == ROOT )
         std::cout<<" I am 0, I send to myself and receive from myself"<<std::endl;
     //Save the X vector to be send as source
     sourceX = X;
     sourceColOrig=RowOrigin();
     destColOrig  =sourceColOrig; //not remove!
     Multiply(0,0,a, X,b, Y );
     //if(rank == ROOT )
     //for( size_t rowIdx=0; rowIdx < RowDim() ; rowIdx++ )
     //{
     //  std::cout<<"Matrix Vector X: "<<X[rowIdx]<<" "<<X[rowIdx]*b<<" "<<b<<" "<<a<<std::endl;
     //  std::cout<<"Matrix Vector Y: "<<Y[rowIdx]<<" "<<Y[rowIdx]*b<<" "<<b<<" "<<a<<std::endl;
     //}
     //Off-site multiplication
     for(integer dx=-1; dx <= 1 ; dx++)
     for(integer dy=-1; dy <= 1 ; dy++)
     if ( dx!=0 || dy !=0 )
     {
         int rectag=1,sendtag=1, source, dest, sourceBuffSize=RowDim(), destBuffSize;
         int sourceCoord[3] ={bIdx(0)+dx,bIdx(1)+dy,0};
         int destCoord[3]   ={bIdx(0)-dx,bIdx(1)-dy,0};
         MPI_Cart_rank(cartComm,sourceCoord,&source);
         MPI_Cart_rank(cartComm,destCoord,&dest);
         MPI_Cart_coords(cartComm, source,2,sourceCoord);
         MPI_Cart_coords(cartComm, dest,2,destCoord);
         MPI_Sendrecv(   &sourceBuffSize ,1 , MPI_INT,dest,sendtag,
                         &destBuffSize   ,1 , MPI_INT,source,rectag,
                         cartComm,MPI_STATUS_IGNORE );
         destX = std::vector<complex>(destBuffSize);
         MPI_Sendrecv(   &sourceColOrig ,1 , MPI_INT,dest,sendtag,
                         &destColOrig   ,1 , MPI_INT,source,rectag,
                         cartComm,MPI_STATUS_IGNORE );
         MPI_Sendrecv(   &sourceX[0] ,sourceBuffSize, MPI_DOUBLE_COMPLEX,dest,sendtag,
                         &destX[0]   ,destBuffSize, MPI_DOUBLE_COMPLEX,source,rectag,
                         cartComm,MPI_STATUS_IGNORE );
         if( rank == ROOT)
         {
             std::cout<<"I am at block: ( "<<bIdx(0)<<" , "<<bIdx(1)<<" )"<<" with "<<dx<<" "<<dy<<std::endl;
             std::cout<<"I send  to dest: "<<dest<<" with coord  ( "<<destCoord[0]<<" , "<<destCoord[1]<<" )"    <<std::endl;
             std::cout<<"The vector Xsource: ";
             for( size_t rowIdx=0; rowIdx < RowDim() ; rowIdx++ )
             if ( std::norm(sourceX[rowIdx] )!=0 )
                 std::cout<<"( "<<rowIdx+RowOrigin()<<" , "<<sourceX[rowIdx].real()<<" ) ";
             std::cout<<std::endl;
             std::cout<<"and receive from source: "<<source<<" with coord  ( "<<sourceCoord[0]<<" , "<<sourceCoord[1]<<" )"  <<std::endl;
             std::cout<<"The vector Xdest: ";
             for( size_t rowIdx=0; rowIdx < RowDim() ; rowIdx++ )
             if ( std::norm(destX[rowIdx] )!=0 )
                 std::cout<<"( "<<rowIdx+RowOrigin()<<" , "<<destX[rowIdx].real()<<" ) ";
             std::cout<<std::endl;
         }
         Multiply(dx,dy,a, destX,1, Y );
     }
 };
size_t tblinalg::TBOperator::NumNonZero ()
Definition at line 1 of file num_non_zero.cpp.
References tblinalg::MatGrid::Block(), tblinalg::MatRow::Dim(), Dim(), tblinalg::MatBlock::GetMatRow(), tblinalg::MatRow::GetMatTuple(), matGrid, numNonZero_, tblinalg::RealZero, and tblinalg::MatTuple::val.
Referenced by WriteIntoFile().
     {
         const size_t dim = Dim();
         if( numNonZero_ == 0)
         for(size_t row=0; row < dim ; row++)
         {
             const MatRow matrow  = matGrid.Block().GetMatRow(row);
             const size_t numElems=matrow.Dim();
             for(size_t elIdx=0; elIdx < numElems ;  elIdx++)
             if( std::norm( matrow.GetMatTuple(elIdx).val ) > RealZero )
                     numNonZero_+=1;
         }
         return numNonZero_;
     }
size_t tblinalg::TBOperator::NumNonZeroInRow (size_t row)
Definition at line 1 of file num_non_zero_in_row.cpp.
References tblinalg::MatGrid::Block(), tblinalg::MatRow::Dim(), tblinalg::MatBlock::GetMatRow(), tblinalg::MatRow::GetMatTuple(), matGrid, tblinalg::RealZero, and tblinalg::MatTuple::val.
Referenced by WriteIntoFile().
 {
     size_t nnz=0;
     const MatRow matrow=matGrid.Block().GetMatRow(row);
     const size_t numElems = matrow.Dim() ;
     for( size_t elIdx=0; elIdx < numElems ; elIdx++)
     if( std::norm( matrow.GetMatTuple(elIdx).val ) > RealZero )
         nnz+=1;
     return nnz;
     return 5;
 }
void tblinalg::TBOperator::ReadOpFromFile (const int dx, const int dy, const std::string opFilename)
Definition at line 1 of file read_op_from_file.cpp.
References tblinalg::MatRow::AddMatTuple(), tblinalg::fileExists(), matGrid, RowDim(), RowEnd(), RowOrigin(), SetRowDim(), SetTotNumOrbs(), tblinalg::MatRow::SortRow(), and TotNumOrbs().
Referenced by ReadOpFromFile().
 {
     //Cheack if the file existas and open the file
     std::string
     localFilename= opFilename+".OP";
     if ( ! fileExists(localFilename) )
     {
         std::cerr<<"File: "<<localFilename<<" not found, return -1;";
         std::exit(-1);
     }
     std::ifstream OpFile  (localFilename.c_str(), std::ofstream::binary);
     //Read the dimension of the matrix, and the total number
     size_t  OpDim, OpNumEntries;
     OpFile>>OpDim>>OpNumEntries;
     SetTotNumOrbs(OpDim);
     //Set initialize the current (x,y) element of the grid
     //to its corresponding site
     if( RowDim()== 0 )
     {
         SetRowDim(OpDim);
         std::cout<<"Warning, OpDim() not setted. Using: "<<OpDim<<std::endl;
     }
     matGrid(dx,dy).SetDim( RowDim() );
     for( size_t row = 0; row < TotNumOrbs() ; ++row )
     {
         bool isMyRow= (row >= RowOrigin() && row < RowEnd() ) ;
         //Get the number of elements per row
         size_t ElemsPerRow;
         OpFile>>ElemsPerRow;
         //Create a row to store the elements
         MatRow matrow;
         //Iterate over the elements
         for( size_t elem=0; elem < ElemsPerRow ; ++elem )
         {
             size_t col; real Reval, Imval;
             OpFile>>col>>Reval>>Imval;
             if( isMyRow )
             matrow.AddMatTuple(col,complex(Reval,Imval) );
         }
         if( isMyRow)
         matGrid(dx,dy).SetMatRow(row-RowOrigin(),matrow.SortRow() );
     }
     OpFile.close();
 };
void tblinalg::TBOperator::WriteIntoFile (std::string label)
Definition at line 2 of file write_into_file.cpp.
References tblinalg::MatRow::AddMatTuple(), tblinalg::MatGrid::Block(), tblinalg::MatTuple::col, tblinalg::MatRow::Dim(), Dim(), tblinalg::MatBlock::GetMatRow(), tblinalg::MatRow::GetMatTuple(), matGrid, NumNonZero(), NumNonZeroInRow(), tblinalg::RealZero, tblinalg::MatRow::SortRow(), and tblinalg::MatTuple::val.
 {
     const size_t dim = Dim();
     std::string opFilename = label + ".OP" ;
     std::ofstream opFile( opFilename.c_str(),  std::ofstream::binary );
         opFile  <<Dim()<<" "
                 <<NumNonZero( ) <<" ";
     for(size_t row=0; row < dim ; row++)
     {
         const MatRow matrow = matGrid.Block().GetMatRow(row);
         const size_t numElems = matrow.Dim() ;
         opFile<<NumNonZeroInRow( row )<<" ";
         MatRow unsortedRow;
         for(size_t elIdx=0;elIdx < numElems ; elIdx++)
         {
             const MatTuple t = matrow.GetMatTuple(elIdx);
             if( std::norm( t.val ) > RealZero )
                 unsortedRow.AddMatTuple(t.col,t.val);
         }
         unsortedRow.SortRow();
         for(size_t elIdx=0;elIdx < unsortedRow.Dim() ; elIdx++)
         {
             const MatTuple t = unsortedRow.GetMatTuple(elIdx) ;
             opFile  <<t.col<<" "
             <<t.val.real()<<" "
             <<t.val.imag()<<" ";
         }
     }
     opFile.close();
 };
void tblinalg::TBOperator::saveTxtCoo (std::string label)
Definition at line 3 of file save_txt_coo.cpp.
References tblinalg::MatRow::AddMatTuple(), tblinalg::MatGrid::Block(), tblinalg::MatTuple::col, tblinalg::MatRow::Dim(), Dim(), tblinalg::MatBlock::GetMatRow(), tblinalg::MatRow::GetMatTuple(), matGrid, tblinalg::RealZero, tblinalg::MatRow::SortRow(), and tblinalg::MatTuple::val.
 {
     const size_t dim = Dim();
     std::string opFilename = label + ".COO" ;
     std::ofstream opFile( opFilename.c_str()  );
     for(size_t row=0;row < dim; row++)
     {
         MatRow unsortedRow;
         const MatRow matrow = matGrid.Block().GetMatRow(row);
         const size_t rowSize = matrow.Dim() ;
         for(size_t elIdx=0;elIdx < rowSize ; elIdx++)
         {
             const MatTuple tuple = matrow.GetMatTuple(elIdx);
             const size_t col = tuple.col;
             const complex val = tuple.val;
             if( std::norm( val ) > RealZero )
             unsortedRow.AddMatTuple(col,val);
         }
     unsortedRow.SortRow();
     for(size_t elIdx=0;elIdx < unsortedRow.Dim() ; elIdx++)
     {
         size_t  col =unsortedRow.GetMatTuple(elIdx).col;
         complex val =unsortedRow.GetMatTuple(elIdx).val;
         opFile  <<row<<" "
         <<col<<" "
         <<val.real()<<" "
         <<val.imag()<<std::endl;
     }
     }
 opFile.close();
 };
void tblinalg::TBOperator::PrintTBOp (const integer dx, const integer dy)
Definition at line 1 of file print_tb_op.cpp.
References matGrid, RowDim(), and RowOrigin().
 {
     for(size_t rowIdx= 0; rowIdx < RowDim() ; rowIdx++)
     for(size_t elem=0;elem < matGrid(dx,dy).GetMatRow(rowIdx).Dim() ; elem++)
     {
         size_t row= RowOrigin() + rowIdx ;
         integer col=matGrid(dx,dy).GetMatRow(rowIdx).GetMatTuple(elem).col;
         complex val=matGrid(dx,dy).GetMatRow(rowIdx).GetMatTuple(elem).val;
         std::cout<<row<<" "<<col<<" "<<val.real()<<" "<<val.imag()<<std::endl;
     }
 };
void tblinalg::TBOperator::ReadOpFromFile (const std::string opFilename) inline
Definition at line 149 of file tb_operator.hpp.
References ReadOpFromFile().
     {
         ReadOpFromFile(-1,-1, opFilename);
     };
void tblinalg::TBOperator::PrintTBOp () inline
Definition at line 154 of file tb_operator.hpp.
     {
         PrintTBOp(-1,-1);
     }
void tblinalg::TBOperator::Rescale (const tblinalg::real shift, const tblinalg::real scal) inline
Definition at line 159 of file tb_operator.hpp.
References Rescale().
     {
         Rescale(-1,-1,  shift, scal );
     };
void tblinalg::TBOperator::SetMpiWorkspace (Indexes _bIdx) inline
Definition at line 165 of file tb_operator.hpp.
References bIdx, cartComm, destColOrig, destX, tblinalg::Indexes::Dim(), RowDim(), RowOrigin(), sourceColOrig, and sourceX.
     {
         bIdx            = _bIdx;
         int sp=2;
         int PBC[3]={1,1,1};
         int blockNum[3]={bIdx.Dim(0),bIdx.Dim(1),bIdx.Dim(2)};
         MPI_Cart_create(MPI_COMM_WORLD, sp , blockNum, PBC,0,&cartComm);
         destX           = std::vector<complex>(RowDim());
         sourceX         = std::vector<complex>(RowDim());
         sourceColOrig   = RowOrigin();
         destColOrig     = RowOrigin();
     };
Member Data Documentation
MatGrid tblinalg::TBOperator::matGrid
Definition at line 34 of file tb_operator.hpp.
Referenced by AddEntry(), Dim(), Multiply(), NumNonZero(), NumNonZeroInRow(), PrintTBOp(), ReadOpFromFile(), Rescale(), saveTxtCoo(), TBOperator(), and WriteIntoFile().
size_t tblinalg::TBOperator::spatialDim_ private
Definition at line 178 of file tb_operator.hpp.
size_t tblinalg::TBOperator::rowDim_ private
Definition at line 178 of file tb_operator.hpp.
Referenced by RowDim(), SetRowDim(), and SetRowOrigin().
size_t tblinalg::TBOperator::rowOrig_ private
Definition at line 178 of file tb_operator.hpp.
Referenced by RowOrigin(), and SetRowOrigin().
size_t tblinalg::TBOperator::rowEnd_ private
Definition at line 178 of file tb_operator.hpp.
Referenced by RowEnd(), SetRowDim(), SetRowEnd(), and SetRowOrigin().
size_t tblinalg::TBOperator::colBufferSize_ private
Definition at line 178 of file tb_operator.hpp.
Referenced by BufferSize(), and TBOperator().
size_t tblinalg::TBOperator::numNonZero_ private
Definition at line 178 of file tb_operator.hpp.
Referenced by NumNonZero().
size_t tblinalg::TBOperator::totNumOrbs_ private
Definition at line 183 of file tb_operator.hpp.
Referenced by SetTotNumOrbs(), and TotNumOrbs().
size_t tblinalg::TBOperator::sourceColOrig private
Definition at line 186 of file tb_operator.hpp.
Referenced by SetMpiWorkspace().
size_t tblinalg::TBOperator::destColOrig private
Definition at line 187 of file tb_operator.hpp.
Referenced by Multiply(), and SetMpiWorkspace().
std::vector<complex> tblinalg::TBOperator::destX private
Definition at line 188 of file tb_operator.hpp.
Referenced by SetMpiWorkspace().
std::vector<complex> tblinalg::TBOperator::sourceX private
Definition at line 189 of file tb_operator.hpp.
Referenced by SetMpiWorkspace().
MPI_Comm tblinalg::TBOperator::cartComm private
Definition at line 190 of file tb_operator.hpp.
Referenced by SetMpiWorkspace().
Indexes tblinalg::TBOperator::bIdx private
Definition at line 191 of file tb_operator.hpp.
Referenced by Multiply(), and SetMpiWorkspace().
The documentation for this class was generated from the following files:
include/tblinalg/tb_operator.hpp
include/tblinalg/tboperator/add_entry.cpp
include/tblinalg/tboperator/multiply.cpp
include/tblinalg/tboperator/num_non_zero.cpp
include/tblinalg/tboperator/num_non_zero_in_row.cpp
include/tblinalg/tboperator/print_tb_op.cpp
include/tblinalg/tboperator/read_op_from_file.cpp
include/tblinalg/tboperator/rescale.cpp
include/tblinalg/tboperator/save_txt_coo.cpp
include/tblinalg/tboperator/set_row_range.cpp
include/tblinalg/tboperator/write_into_file.cpp