tblinalg: tblinalg::Indexes Class Reference
tblinalg::Indexes Class Reference
#include <indexes.hpp>
Public Member Functions
Indexes (const size_t _numIndexes)
integer operator() (const size_t pos) const
integer & operator() (const size_t pos)
size_t Dim (const size_t pos) const
size_t & Dim (const size_t pos)
size_t NumOfIndexes () const
integer ReduceToOne () const
integer ScatterToAll (size_t idx)
Private Attributes
size_t numIndexes_
std::vector< integer > idxArray_
std::vector< size_t > dimArray_
Detailed Description
Definition at line 15 of file indexes.hpp.
Constructor & Destructor Documentation
tblinalg::Indexes::Indexes (const size_t _numIndexes) inline
Definition at line 20 of file indexes.hpp.
References dimArray_, and idxArray_.
                                      :
     numIndexes_(_numIndexes)
     {
         idxArray_= std::vector<integer>( _numIndexes );
         dimArray_= std::vector<size_t>( _numIndexes );
     }
Member Function Documentation
integer tblinalg::Indexes::operator() (const size_t pos) const inline
Definition at line 29 of file indexes.hpp.
References idxArray_, and NumOfIndexes().
     {
         assert( pos < NumOfIndexes());
         return idxArray_[pos];
     }
integer& tblinalg::Indexes::operator() (const size_t pos) inline
Definition at line 35 of file indexes.hpp.
References idxArray_, and NumOfIndexes().
     {
         assert( pos < NumOfIndexes());
         return idxArray_[pos];
     }
size_t tblinalg::Indexes::Dim (const size_t pos) const inline
Definition at line 42 of file indexes.hpp.
References dimArray_, and NumOfIndexes().
Referenced by tblinalg::MapFromLatticeToDD(), and tblinalg::TBOperator::SetMpiWorkspace().
     {
         assert( pos < NumOfIndexes());
         return dimArray_[pos];
     }
size_t& tblinalg::Indexes::Dim (const size_t pos) inline
Definition at line 48 of file indexes.hpp.
References dimArray_, and NumOfIndexes().
     {
         assert( pos < NumOfIndexes());
         return dimArray_[pos];
     }
size_t tblinalg::Indexes::NumOfIndexes () const inline
Definition at line 55 of file indexes.hpp.
References numIndexes_.
Referenced by Dim(), operator()(), ReduceToOne(), and ScatterToAll().
     {
         return numIndexes_ ;
     }
integer tblinalg::Indexes::ReduceToOne () const inline
Definition at line 60 of file indexes.hpp.
References dimArray_, idxArray_, and NumOfIndexes().
Referenced by tblinalg::MapFromLatticeToDD(), and tblinalg::TBOperator::Multiply().
     {
         integer singleIdx=idxArray_[0];
         for ( size_t pos=1 ; pos < NumOfIndexes(); pos++ )
             singleIdx = singleIdx*dimArray_[pos] + idxArray_[pos] ;
         return singleIdx;
     }
integer tblinalg::Indexes::ScatterToAll (size_t idx) inline
Definition at line 70 of file indexes.hpp.
References dimArray_, idxArray_, and NumOfIndexes().
     {
         for ( size_t pos=0 ; pos < NumOfIndexes() ; pos++ )
         {   const size_t inv_pos=NumOfIndexes()-1-pos;
             idxArray_[inv_pos] =( idx )%dimArray_[inv_pos];
             idx=idx/dimArray_[inv_pos];
         }
     }
Member Data Documentation
size_t tblinalg::Indexes::numIndexes_ private
Definition at line 80 of file indexes.hpp.
Referenced by NumOfIndexes().
std::vector<integer> tblinalg::Indexes::idxArray_ private
Definition at line 81 of file indexes.hpp.
Referenced by Indexes(), operator()(), ReduceToOne(), and ScatterToAll().
std::vector<size_t> tblinalg::Indexes::dimArray_ private
Definition at line 82 of file indexes.hpp.
Referenced by Dim(), Indexes(), ReduceToOne(), and ScatterToAll().
The documentation for this class was generated from the following file:
include/tblinalg/indexes.hpp