tblinalg: tblinalg Namespace Reference
tblinalg Namespace Reference
This method adds two integers.
Classes
class Indexes
class MatBlock
class MatGrid
class MatRow
struct MatTuple
struct sortTuplebyCol
struct Structural
class TBOperator
Typedefs
typedef double real
typedef std::complex< real > complex
typedef int integer
Functions
void MapFromLatticeToDD (Indexes idx, Indexes bIdx, Indexes tIdx, std::map< size_t, size_t > &mymap)
bool fileExists (const std::string &name)
std::string ToString (const int val)
void Dot (const size_t root, const std::vector< complex > &x, const std::vector< complex > &y, complex &result)
void Dot (const std::vector< complex > &x, const std::vector< complex > &y, complex &result)
void Norm (const size_t root, const std::vector< complex > &x, real &result)
void Norm (const std::vector< complex > &x, real &result)
void Normalize (std::vector< complex > &x)
void FillRandomFill (std::vector< complex > &x)
void Fill (std::vector< complex > &x, complex C)
void SyncRandomFill (const size_t globDim, const size_t rowOrig, std::vector< complex > &x)
Variables
real RealZero =std::numeric_limits<real>::epsilon()
Detailed Description
This method adds two integers.
Parameters
a First integer to add.
b Second integer to add.
Returns
The sum of both parameters.
Typedef Documentation
typedef double tblinalg::real
Definition at line 23 of file types_definitions.hpp.
typedef std::complex<real> tblinalg::complex
Definition at line 25 of file types_definitions.hpp.
typedef int tblinalg::integer
Definition at line 26 of file types_definitions.hpp.
Function Documentation
void tblinalg::MapFromLatticeToDD (Indexes idx, Indexes bIdx, Indexes tIdx, std::map< size_t, size_t > & mymap)
Definition at line 17 of file domain_decomposition.hpp.
References tblinalg::Indexes::Dim(), and tblinalg::Indexes::ReduceToOne().
     {
         //  The first step of the domain decomposition is to look within all
         // the sites beloning to the lattice, which one belong to a given
         // domain and index it accordingly
         size_t rowIdx=0;
         for(bIdx(0)=0; bIdx(0)< bIdx.Dim(0) ; bIdx(0)++)
         for(bIdx(1)=0; bIdx(1)< bIdx.Dim(1) ; bIdx(1)++)
         for(bIdx(2)=0; bIdx(2)< bIdx.Dim(2) ; bIdx(2)++)
         {
             //  It is assume that this loop will go through all the sites in the
             // system, no matter is is disconected from the lattice.
             //  Therefore, the first step is to separate the row indices
             // in domains
             for(idx(0)=0;idx(0)<idx.Dim(0) ; idx(0)++)
             for(idx(1)=0;idx(1)<idx.Dim(1) ; idx(1)++)
             for(idx(2)=0;idx(2)<idx.Dim(2) ; idx(2)++)
             for(idx(3)=0;idx(3)<idx.Dim(3) ; idx(3)++)
             for(idx(4)=0;idx(4)<idx.Dim(4) ; idx(4)++)
             {
                 const size_t
                 row= idx.ReduceToOne();
                 if(
                     (idx(0)>= bIdx(0)*tIdx.Dim(0) && idx(0)< (bIdx(0)+1)*tIdx.Dim(0) )
                     &&
                     (idx(1)>= bIdx(1)*tIdx.Dim(1) && idx(1)< (bIdx(1)+1)*tIdx.Dim(1) )
                     &&
                     (idx(2)>= bIdx(2)*tIdx.Dim(2) && idx(2)< (bIdx(2)+1)*tIdx.Dim(2) )
                     )
                 {
                     mymap[row]= rowIdx ;
                     rowIdx+=1;
 //                  std::cout<<"map"<<row<<" "<<rowIdx<<std::endl;
                 }
             }
         }
     };
bool tblinalg::fileExists (const std::string & name) inline
Definition at line 11 of file input_output.hpp.
Referenced by tblinalg::Structural::loadtxt(), tblinalg::TBOperator::ReadOpFromFile(), and tblinalg::TBOperator::SetRowRange().
{
   struct stat buffer;
   return (stat (name.c_str(), &buffer) == 0);
 };
std::string tblinalg::ToString (const int val)
Definition at line 10 of file string_util.h.
     {
         std::stringstream ss;
         ss<<val;
         return ss.str();
     };
void tblinalg::Dot (const size_t root, const std::vector< complex > & x, const std::vector< complex > & y, complex & result)
Definition at line 11 of file vector_operations.hpp.
References MPI_TBLINALG_COMPLEX.
     {
         const size_t dim = x.size() ;
         complex partial_result= 0 ;
         for( std::size_t i = 0 ; i< dim ; i++ )
             partial_result+= std::conj(x[i])*y[i] ;
         result=0.0;
         MPI_Reduce( &partial_result, &result, 1,
                     MPI_TBLINALG_COMPLEX,
                     MPI_SUM,
                     root,
                     MPI_COMM_WORLD);
     }
void tblinalg::Dot (const std::vector< complex > & x, const std::vector< complex > & y, complex & result)
Definition at line 32 of file vector_operations.hpp.
References MPI_TBLINALG_COMPLEX.
     {
         const size_t dim = x.size() ;
         complex partial_result= 0 ;
         for( std::size_t i = 0 ; i< dim ; i++ )
             partial_result+= std::conj(x[i])*y[i] ;
         result=0.0;
         MPI_Allreduce( &partial_result, &result, 1,
                         MPI_TBLINALG_COMPLEX,
                         MPI_SUM,
                         MPI_COMM_WORLD);
     };
void tblinalg::Norm (const size_t root, const std::vector< complex > & x, real & result)
Definition at line 52 of file vector_operations.hpp.
References MPI_TBLINALG_COMPLEX.
Referenced by Normalize().
     {
         const size_t dim = x.size() ;
         real partial_result= 0 ;
         for( std::size_t i = 0 ; i< dim ; i++ )
             partial_result+= std::norm(x[i]);
         MPI_Reduce( &partial_result, &result, 1,
                         MPI_TBLINALG_COMPLEX,
                         MPI_SUM,
                         root,
                         MPI_COMM_WORLD);
         result = sqrt( result ) ;
     };
void tblinalg::Norm (const std::vector< complex > & x, real & result)
Definition at line 71 of file vector_operations.hpp.
References MPI_TBLINALG_COMPLEX.
     {
         const size_t dim = x.size() ;
         real partial_result= 0 ;
         for( std::size_t i = 0 ; i< dim ; i++ )
             partial_result+= std::norm(x[i]);
         MPI_Allreduce( &partial_result, &result, 1,
                         MPI_TBLINALG_COMPLEX,
                         MPI_SUM,
                         MPI_COMM_WORLD);
         result = sqrt( result ) ;
     };
void tblinalg::Normalize (std::vector< complex > & x)
Definition at line 87 of file vector_operations.hpp.
References Norm().
     {
         const size_t dim = x.size() ;
         real  nrm = 0 ;
         Norm( x, nrm );
         const real invNorm = 1/nrm ;
         for( std::size_t i = 0 ; i< dim ; i++ )
              x[i]*=invNorm;
     };
void tblinalg::FillRandomFill (std::vector< complex > & x)
Definition at line 101 of file vector_operations.hpp.
References I().
     {
         const size_t dim = x.size() ;
         for( std::size_t i = 0 ; i< dim ; i++ )
         {
             const real phi = 2.0*M_PI*( (real)rand()/(real)RAND_MAX - 0.5 ) ;
             x[i] = std::exp( I * phi);
         }
     };
void tblinalg::Fill (std::vector< complex > & x, complex C)
Definition at line 112 of file vector_operations.hpp.
     {
         const size_t dim = x.size() ;
         for( std::size_t i = 0 ; i< dim ; i++ )
             x[i] = C;
     };
void tblinalg::SyncRandomFill (const size_t globDim, const size_t rowOrig, std::vector< complex > & x)
Definition at line 121 of file vector_operations.hpp.
References I().
     {
         const size_t dim = x.size() ;
         for( std::size_t i = 0 ; i< globDim ; i++ )
         {
             const integer idx = i - rowOrig ;
             const real phi = 2.0*M_PI*( (real)rand()/(real)RAND_MAX - 0.5 ) ;
             if ( idx >= 0  && idx < dim )
                 x[idx] = std::exp( I * phi);
         }
     };
Variable Documentation
real tblinalg::RealZero =std::numeric_limits<real>::epsilon()
Definition at line 27 of file types_definitions.hpp.
Referenced by tblinalg::TBOperator::NumNonZero(), tblinalg::TBOperator::NumNonZeroInRow(), tblinalg::TBOperator::saveTxtCoo(), and tblinalg::TBOperator::WriteIntoFile().